version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  MAVEN_VERSION: 3.6.3
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

branches:
  only:
    - master
  except:
    - gh-pages
install:
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package --batch-mode -Dmaven.test.skip=true
test_script:
  - mvn clean install --batch-mode
cache:
  - C:\maven\ -> appveyor.yml
  - C:\Users\appveyor\.m2\ -> pom.xml